from __future__ import annotations

from pathlib import Path

import numpy as np


class DeformationPrior:
    """PCA subspace of real face deformations built from FaMoS training pairs.

    Used as an ICP regularizer: the current deformation is soft-constrained to
    stay near the subspace of real expressions.
    """

    def __init__(self, mean: np.ndarray, components: np.ndarray, singular_values: np.ndarray):
        # mean: (V, 3) float32
        # components: (k, V*3) float32 — rows are principal axes (unit vectors)
        # singular_values: (k,) float32
        self.mean = mean.astype(np.float32)
        self.components = components.astype(np.float32)
        self.singular_values = singular_values.astype(np.float32)
        self.vertex_count: int = int(mean.shape[0])
        self.n_components: int = int(components.shape[0])
        self._mean_flat: np.ndarray = self.mean.reshape(-1).astype(np.float64)
        self._components_f64: np.ndarray = self.components.astype(np.float64)

    def project(self, vertices: np.ndarray) -> np.ndarray:
        """Project vertices onto the learned subspace.

        Returns the nearest point in the PCA subspace — used as the PCA
        target position in the ICP linear system.

        vertices: (V, 3)
        returns: (V, 3) float64
        """
        x_flat = vertices.reshape(-1).astype(np.float64)
        delta = x_flat - self._mean_flat                         # (V*3,)
        coeffs = self._components_f64 @ delta                   # (k,)
        x_proj = self._mean_flat + self._components_f64.T @ coeffs  # (V*3,)
        return x_proj.reshape(self.vertex_count, 3)

    def save(self, path: str | Path) -> None:
        np.savez_compressed(
            str(path),
            mean=self.mean,
            components=self.components,
            singular_values=self.singular_values,
        )

    @classmethod
    def load(cls, path: str | Path) -> "DeformationPrior":
        data = np.load(str(path))
        if {"mean", "components", "singular_values"}.issubset(set(data.files)):
            return cls(data["mean"], data["components"], data["singular_values"])

        # Compatibility with the meeting/demo prior generated by
        # scripts/learn_famos_deformation_prior.py.  That script stores PCA
        # modes as (k, V, 3); Semantic ICP needs flattened component rows.
        if {"mean_vertices", "modes"}.issubset(set(data.files)):
            mean = data["mean_vertices"]
            modes = data["modes"]
            components = modes.reshape(modes.shape[0], -1)
            if "singular_values" in data.files:
                singular_values = data["singular_values"]
            elif "explained_variance_ratio" in data.files:
                singular_values = np.sqrt(np.maximum(data["explained_variance_ratio"], 1e-12))
            elif "explained_variance" in data.files:
                singular_values = np.sqrt(np.maximum(data["explained_variance"], 1e-12))
            else:
                singular_values = np.ones(components.shape[0], dtype=np.float32)
            return cls(mean, components, singular_values)

        raise ValueError(
            f"Unsupported deformation prior format at {path}; expected "
            "mean/components/singular_values or mean_vertices/modes."
        )

    @classmethod
    def build(cls, pairs_dir: str | Path, n_components: int = 64) -> "DeformationPrior":
        """Build PCA model from target_vertices.npy files under pairs_dir.

        pairs_dir: directory containing pair_XXXXXX/target_vertices.npy
        n_components: number of PCA modes to keep
        """
        pairs_dir = Path(pairs_dir)
        target_files = sorted(pairs_dir.glob("**/target_vertices.npy"))
        if not target_files:
            raise ValueError(f"No target_vertices.npy files found under {pairs_dir}")

        targets: list[np.ndarray] = []
        for f in target_files:
            v = np.load(str(f)).astype(np.float32)
            targets.append(v)

        vertex_count = targets[0].shape[0]
        n = len(targets)
        print(f"[build-prior] {n} target meshes, {vertex_count} vertices each")

        D = np.stack([t.reshape(-1) for t in targets], axis=0)   # (N, V*3)
        mean_flat = D.mean(axis=0)
        D_centered = (D - mean_flat).astype(np.float32)

        k = min(n_components, n - 1, D_centered.shape[1])
        print(f"[build-prior] SVD k={k} on {D_centered.shape} ...")

        if n <= 5000:
            U, S, Vt = np.linalg.svd(D_centered.astype(np.float64), full_matrices=False)
            Vt = Vt[:k].astype(np.float32)
            S = S[:k].astype(np.float32)
        else:
            from scipy.sparse.linalg import svds
            _, S, Vt = svds(D_centered.astype(np.float64), k=k)
            order = np.argsort(-S)
            S, Vt = S[order].astype(np.float32), Vt[order].astype(np.float32)

        mean_arr = mean_flat.reshape(vertex_count, 3).astype(np.float32)
        print(f"[build-prior] Top-5 singular values: {S[:5]}")
        return cls(mean_arr, Vt, S)


def build_deformation_prior(pairs_dir: str | Path, out: str | Path, n_components: int = 64) -> dict[str, object]:
    """CLI entry-point: build and save prior, return summary dict."""
    prior = DeformationPrior.build(pairs_dir, n_components=n_components)
    out_path = Path(out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    prior.save(out_path)
    return {
        "prior_path": str(out_path),
        "vertex_count": prior.vertex_count,
        "n_components": prior.n_components,
        "top_singular_values": prior.singular_values[:10].tolist(),
    }
